version: '3'
services:
  nginx:
    build: ./nginx
    links:
      - pomodory
    ports:
      - "80:80"
      - "443:443"
  db:
    build: ./database/ 
  pomodory:
    build: ./
    links:
      - db
    ports:
      - "8081:8081"  
    depends_on: 
    - db